apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitops-mastery-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitops-mastery
  template:
    metadata:
      labels:
        app: gitops-mastery
    spec:
      containers:
        - name: practice-container
          image: ghcr.io/craztool/gitops-mastery:56af2ea8ee819213716e34bf39e3884d18714bcf
          ports:
            - containerPort: 8080