apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitops-mastery-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitops-mastery
  template:
    metadata:
      labels:
        app: gitops-mastery
    spec:
      containers:
        - name: practice-container
          image: ghcr.io/craztool/gitops-mastery:latest
          ports:
            - containerPort: 8080